use http::Method;

pub enum APIEndpoint {
    GetUpdates,
    GetMe,
    SendMessage,
    SetMyCommands,
    GetMyCommands,
    ForwardMessage,
    SendPhoto,
    SendAudio,
    SendDocument,
    SendVideo,
    SendAnimation,
    SendVoice,
    SendVideoNote,
    SendMediaGroup,
    SendLocation,
    EditMessageLiveLocation,
    StopMessageLiveLocation,
    SendVenue,
    SendContact,
    SendPoll,
    SendDice,
    SendChatAction,
    GetUserProfilePhotos,
    GetFile,
    KickChatMember,
    UnbanChatMember,
    RestrictChatMember,
    PromoteChatMember,
    SetChatAdministratorCustomTitle,
    SetChatPermissions,
    ExportChatInviteLink,
    SetChatPhoto,
    DeleteChatPhoto,
    SetChatTitle,
    SetChatDescription,
    PinChatMessage,
    UnpinChatMessage,
    LeaveChat,
    GetChat,
    GetChatAdministrators,
    GetChatMembersCount,
    GetChatMember,
    SetChatStickerSet,
    DeleteChatStickerSet,
    AnswerCallbackQuery,
    EditMessageText,
    EditMessageCaption,
    EditMessageMedia,
    EditMessageReplyMarkup,
    StopPoll,
    DeleteMessage,
    SendSticker,
    GetStickerSet,
    UploadStickerFile,
    CreateNewStickerSet,
    AddStickerToSet,
    SetStickerPositionInSet,
    DeleteStickerFromSet,
    SetStickerSetThumb,
    AnswerInlineQuery,
    SendInvoice,
    AnswerShippingQuery,
    AnswerPreCheckoutQuery,
    SendGame,
    SetGameScore,
    GetGameHighScores,
    SetWebhook,
    SetPassportDataErrors,
    DeleteWebhook,
    GetWebhookInfo,
}

impl APIEndpoint {
    pub fn as_str(&self) -> &str {
        match *self {
            Self::GetUpdates => "getUpdates",
            Self::GetMe => "getMe",
            Self::SendMessage => "sendMessage",
            Self::SetMyCommands => "setMyCommands",
            Self::GetMyCommands => "getMyCommands",
            Self::ForwardMessage => "forwardMessage",
            Self::SendPhoto => "sendPhoto",
            Self::SendAudio => "sendAudio",
            Self::SendDocument => "sendDocument",
            Self::SendVideo => "sendVideo",
            Self::SendAnimation => "sendAnimation",
            Self::SendVoice => "sendVoice",
            Self::SendVideoNote => "sendVideoNote",
            Self::SendMediaGroup => "sendMediaGroup",
            Self::SendLocation => "sendLocation",
            Self::EditMessageLiveLocation => "editMessageLiveLocation",
            Self::StopMessageLiveLocation => "stopMessageLiveLocation",
            Self::SendVenue => "sendVenue",
            Self::SendContact => "sendContact",
            Self::SendPoll => "sendPoll",
            Self::SendDice => "sendDice",
            Self::SendChatAction => "sendChatAction",
            Self::GetUserProfilePhotos => "getUserProfilePhotos",
            Self::GetFile => "getFile",
            Self::KickChatMember => "kickChatMember",
            Self::UnbanChatMember => "unbanChatMember",
            Self::RestrictChatMember => "restrictChatMember",
            Self::PromoteChatMember => "promoteChatMember",
            Self::SetChatAdministratorCustomTitle => "setChatAdministratorCustomTitle",
            Self::SetChatPermissions => "setChatPermissions",
            Self::ExportChatInviteLink => "exportChatInviteLink",
            Self::SetChatPhoto => "setChatPhoto",
            Self::DeleteChatPhoto => "deleteChatPhoto",
            Self::SetChatTitle => "setChatTitle",
            Self::SetChatDescription => "setChatDescription",
            Self::PinChatMessage => "pinChatMessage",
            Self::UnpinChatMessage => "unpinChatMessage",
            Self::LeaveChat => "leaveChat",
            Self::GetChat => "getChat",
            Self::GetChatAdministrators => "getChatAdministrators",
            Self::GetChatMembersCount => "getChatMembersCount",
            Self::GetChatMember => "getChatMember",
            Self::SetChatStickerSet => "setChatStickerSet",
            Self::DeleteChatStickerSet => "deleteChatStickerSet",
            Self::AnswerCallbackQuery => "answerCallbackQuery",
            Self::EditMessageText => "editMessageText",
            Self::EditMessageCaption => "editMessageCaption",
            Self::EditMessageMedia => "editMessageMedia",
            Self::EditMessageReplyMarkup => "editMessageReplyMarkup",
            Self::StopPoll => "stopPoll",
            Self::DeleteMessage => "deleteMessage",
            Self::SendSticker => "sendSticker",
            Self::GetStickerSet => "getStickerSet",
            Self::UploadStickerFile => "uploadStickerFile",
            Self::CreateNewStickerSet => "createNewStickerSet",
            Self::AddStickerToSet => "addStickerToSet",
            Self::SetStickerPositionInSet => "setStickerPositionInSet",
            Self::DeleteStickerFromSet => "deleteStickerFromSet",
            Self::SetStickerSetThumb => "setStickerSetThumb",
            Self::AnswerInlineQuery => "answerInlineQuery",
            Self::SendGame => "sendGame",
            Self::SetGameScore => "setGameScore",
            Self::GetGameHighScores => "getGameHighScores",
            Self::SendInvoice => "sendInvoice",
            Self::AnswerShippingQuery => "answerShippingQuery",
            Self::AnswerPreCheckoutQuery => "answerPreCheckoutQuery",
            Self::SetWebhook => "setWebHook",
            Self::SetPassportDataErrors => "setPassportDataErrors",
            Self::DeleteWebhook => "deleteWebhook",
            Self::GetWebhookInfo => "getWebhookInfo"
        }
    }

    pub fn get_method(&self) -> Method {
        match *self {
            Self::GetUpdates => Method::GET,
            Self::GetMe => Method::GET,
            Self::SendMessage => Method::POST,
            Self::GetMyCommands => Method::GET,
            Self::SetMyCommands => Method::POST,
            Self::ForwardMessage => Method::POST,
            Self::SendPhoto => Method::POST,
            Self::SendAudio => Method::POST,
            Self::SendDocument => Method::POST,
            Self::SendVideo => Method::POST,
            Self::SendAnimation => Method::POST,
            Self::SendVoice => Method::POST,
            Self::SendVideoNote => Method::POST,
            Self::SendMediaGroup => Method::POST,
            Self::SendLocation => Method::POST,
            Self::EditMessageLiveLocation => Method::POST,
            Self::StopMessageLiveLocation => Method::POST,
            Self::SendVenue => Method::POST,
            Self::SendContact => Method::POST,
            Self::SendPoll => Method::POST,
            Self::SendDice => Method::POST,
            Self::SendChatAction => Method::POST,
            Self::GetUserProfilePhotos => Method::GET,
            Self::GetFile => Method::GET,
            Self::KickChatMember => Method::POST,
            Self::UnbanChatMember => Method::POST,
            Self::RestrictChatMember => Method::POST,
            Self::PromoteChatMember => Method::POST,
            Self::SetChatAdministratorCustomTitle => Method::POST,
            Self::SetChatPermissions => Method::POST,
            Self::ExportChatInviteLink => Method::POST,
            Self::SetChatPhoto => Method::POST,
            Self::DeleteChatPhoto => Method::POST,
            Self::SetChatTitle => Method::POST,
            Self::SetChatDescription => Method::POST,
            Self::PinChatMessage => Method::POST,
            Self::UnpinChatMessage => Method::POST,
            Self::LeaveChat => Method::POST,
            Self::GetChat => Method::GET,
            Self::GetChatAdministrators => Method::GET,
            Self::GetChatMembersCount => Method::GET,
            Self::GetChatMember => Method::GET,
            Self::SetChatStickerSet => Method::POST,
            Self::DeleteChatStickerSet => Method::POST,
            Self::AnswerCallbackQuery => Method::POST,
            Self::EditMessageText => Method::POST,
            Self::EditMessageCaption => Method::POST,
            Self::EditMessageMedia => Method::POST,
            Self::EditMessageReplyMarkup => Method::POST,
            Self::StopPoll => Method::POST,
            Self::DeleteMessage => Method::POST,
            Self::SendSticker => Method::POST,
            Self::GetStickerSet => Method::GET,
            Self::UploadStickerFile => Method::POST,
            Self::CreateNewStickerSet => Method::POST,
            Self::AddStickerToSet => Method::POST,
            Self::SetStickerPositionInSet => Method::POST,
            Self::DeleteStickerFromSet => Method::POST,
            Self::SetStickerSetThumb => Method::POST,
            Self::AnswerInlineQuery => Method::POST,
            Self::SendGame => Method::POST,
            Self::SetGameScore => Method::POST,
            Self::GetGameHighScores => Method::GET,
            Self::SendInvoice => Method::POST,
            Self::AnswerShippingQuery => Method::POST,
            Self::AnswerPreCheckoutQuery => Method::POST,
            Self::SetWebhook => Method::POST,
            Self::SetPassportDataErrors => Method::POST,
            Self::DeleteWebhook => Method::POST,
            Self::GetWebhookInfo => Method::GET
        }
    }
}

impl std::fmt::Display for APIEndpoint {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl std::fmt::Debug for APIEndpoint {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_tuple("telegram::APIEndpoint")
            .field(&self.as_str().to_owned())
            .finish()
    }
}
